# Site settings
title: Software development company | Agile Development
keywords: Freshcode, blog, software development, web development methods, outsourcing, technologies, news
description: Freshcode is a software development outsourcing company with a team of web and mobile developers who provide a wide range of services following agile methods.
email: alex.freshcode@gmail.com
baseurl: ""
url: "http://freshcodeit.com"
twitter_username: "@FreshCode1"
github_username: "Fresh-code"

# Build settings
gems:
  - jekyll-sitemap
show_drafts: false
adaptive_image:
     cache: 2592000
     srcset:
       - 1920
       - 1000
       - 600
       - 320
     sizes:
       - 1920px
       - 100vw
include:
  - _pages
exclude:
  - _assets-cache
markdown: kramdown
permalink: pretty

