# Site settings
title: Software development company | Freshcode
keywords: Freshcode, blog, software development, web development methods, outsourcing, technologies, news
description: Read the latest Freshcode news and updates in software development, web development methods, outsourcing principles, etc.
email: alex.freshcode@gmail.com
baseurl: ""
url: "http://freshcodeit.com"
twitter_username: "@FreshCode1"
github_username: "Fresh-code"

# Build settings
show_drafts: false
adaptive_image:
     cache: 2592000
     srcset:
       - 1920
       - 1000
       - 600
       - 320
     sizes:
       - 1920px
       - 100vw
include:
  - _pages
exclude:
  - _assets-cache
markdown: kramdown
permalink: pretty

